require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - "db/schema.rb"
    - "bin/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics:
  Enabled: false

Layout/LineLength:
  Max: 140
